version: "3.9"
services:
  api-server:
    image: ismail26/blog-server:1.0
    environment:
      - NODE_ENV=production
      - PORT=5000
      - mongoURI=mongodb://mongo:27017/blog_prod
      - accessKeyId=AKIAYVTH5UHMENEA6THQ
      - secretAccessKey=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
      - googleClientID=651703767902-6r273o5sv15dn81h1uplck7e9s8ptfbg.apps.googleusercontent.com
      - googleClientSecret=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
      - cookieKey=123123123
      - redisUrl=redis://redis:6379
    ports:
      - "5000:5000"
    networks: 
      - blog-app
    depends_on: 
      - mongo
      - redis
  mongo:
    image: mongo:3.6.19
    ports: 
      - "27017:27017"
    restart: always
    networks: 
      - blog-app
    volumes:
      - mongo-data:/data/db 
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    command: redis-server
    networks: 
      - blog-app 
    volumes:
      - redis-data:/data
networks:
  blog-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local